# Generated by Django 4.2.6 on 2023-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movie_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='posted',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
