# Generated by Django 4.2.6 on 2023-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_link_network_quality_tag_movie_links_movie_networks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='networks',
            field=models.ManyToManyField(to='core.network'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
