# Generated by Django 4.2.6 on 2023-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movie_networks_alter_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
