# Generated by Django 4.2.6 on 2023-10-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quality_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tags',
            new_name='language',
        ),
    ]
