# Generated by Django 4.2.6 on 2023-10-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_link_name_alter_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='languages',
        ),
    ]
