# Generated by Django 4.2.6 on 2023-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_posted_movie_published_movie_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
