# Generated by Django 4.2.6 on 2023-10-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_link_created_link_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
