# Generated by Django 4.2.6 on 2023-10-29 04:28

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_movie_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name_plural': 'qualities'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
